// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<UGSTutorialCloud.PlayerDataResponse> HandlePlayerSignIn()
        {
            return await k_Service.CallModuleEndpointAsync<UGSTutorialCloud.PlayerDataResponse>(
                "UGSTutorialCloud",
                "HandlePlayerSignIn",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> SayHello(string name)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "UGSTutorialCloud",
                "SayHello",
                new Dictionary<string, object>()
                {
                    {"name", name},
                });
        }

        public async Task<string> HandleNewPlayerNameEntry(string newName)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "UGSTutorialCloud",
                "HandleNewPlayerNameEntry",
                new Dictionary<string, object>()
                {
                    {"newName", newName},
                });
        }
    }
}
