// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class StoreServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public StoreServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<UGSTutorialCloud.PlayerEconomyData> VirtualPurchaseHealthPotion()
        {
            return await k_Service.CallModuleEndpointAsync<UGSTutorialCloud.PlayerEconomyData>(
                "UGSTutorialCloud",
                "VirtualPurchaseHealthPotion",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<UGSTutorialCloud.PlayerEconomyData> ProcessRealMoneyPurchase(string productId, string receipt, double localPrice, string currencyCode)
        {
            return await k_Service.CallModuleEndpointAsync<UGSTutorialCloud.PlayerEconomyData>(
                "UGSTutorialCloud",
                "ProcessRealMoneyPurchase",
                new Dictionary<string, object>()
                {
                    {"productId", productId},
                    {"receipt", receipt},
                    {"localPrice", localPrice},
                    {"currencyCode", currencyCode},
                });
        }
    }
}
